ProductQRCodeReadWithDynamic/Controllers/CamController.cs
using Microsoft.AspNetCore.Mvc;
using ProductQRCodeReadWithDynamic.Entities;
using ProductQRCodeReadWithDynamic.Repositories.Abstractions;
using ProductQRCodeReadWithDynamic.Repositories.Concretes;

namespace ProductQRCodeReadWithDynamic.Controllers
{
    public class CamController : Controller
    {
        private readonly IProductWriteRepository _productWriteRepository;
        private readonly IProductReadRepository _productReadRepository;
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly INotificationWriteRepository _notificationWriteRepository;
        public CamController(IProductWriteRepository productWriteRepository, IProductReadRepository productReadRepository, IWebHostEnvironment hostingEnvironment, IHttpContextAccessor httpContextAccessor, INotificationWriteRepository notificationWriteRepository)
        {
            _productWriteRepository = productWriteRepository;
            _productReadRepository = productReadRepository;
            _hostingEnvironment = hostingEnvironment;
            _httpContextAccessor = httpContextAccessor;
            _notificationWriteRepository = notificationWriteRepository;
        }

        [HttpGet]
        public IActionResult GetCam()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetCam(string productCode)
        {
            if (productCode != null)
            {
                StaticStrings.Properties.HubProperties.readProductCode = productCode;
                Product product = await _productReadRepository.GetFilter(p => p.ProductCode == productCode && p.IsSuccess == true);
                product.ReadCount += 1;
                bool result = await _productWriteRepository.UpdateAsync(product);
                return RedirectToAction("Index", "Product");
            }
            return View();
        }


        [HttpGet]
        public IActionResult GetCamForUpdated()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> GetCamForUpdated(string updatedCode)
        {
            string newProductCode = _httpContextAccessor.HttpContext.Session.GetString("NewProductCode");
            string newUpdatedCode = _httpContextAccessor.HttpContext.Session.GetString("NewUpdatedCode");
            Product product = await _productReadRepository.GetFilter(p => p.ProductCode == newProductCode && p.UpdatedCode == Guid.Parse(newUpdatedCode) && p.IsSuccess == false);

            if (product.UpdatedCode == Guid.Parse(updatedCode))
            {
                product.IsSuccess = true;
                product.UpdatedDate = DateTime.Now;
                bool result = await _productWriteRepository.UpdateAsync(product);
                if (result)
                {
                    string oldUpdatedCode = _httpContextAccessor.HttpContext.Session.GetString("OldProductCode");
                    Product oldProduct = await _productReadRepository.GetFilter(p => p.ProductCode == oldUpdatedCode && p.IsSuccess == true);
                    oldProduct.IsSuccess = false;
                    bool result2 = await _productWriteRepository.UpdateAsync(oldProduct);
                    await _notificationWriteRepository.AddAsync(new()
                    {
                        Message = "Product Updated Successfully !",
                        MessageType = "Personal",
                        Email = _httpContextAccessor.HttpContext.Session.GetString("Email"),
                        IsSuccess = true
                    });
                    return RedirectToAction("Index", "Product");
                }
            }
            else
            {
                await _notificationWriteRepository.AddAsync(new()
                {
                    Message = "Product Updated Unsuccessfully !!!!",
                    MessageType = "Personal",
                    Email = _httpContextAccessor.HttpContext.Session.GetString("Email"),
                    IsSuccess = true
                });
                return View();
            }
            return View();
        }
    }
}

ProductQRCodeReadWithDynamic/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccesor;
@using Microsoft.AspNetCore.Authentication.Cookies
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser<int>> SignInManager;

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductQRCodeReadWithDynamic</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductQRCodeReadWithDynamic.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css"
        integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home"
                    asp-action="Index">ProductQRCodeReadWithDynamic</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication"
                                asp-action="Login">Login</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication"
                                asp-action="SignOut">SignOut</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentication"
                                asp-action="Register">Register</a>
                        </li>
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product"
                                asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cam" asp-action="GetCam">Read
                                Code</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <input type="hidden" id="hfEmail" value="@HttpContextAccesor.HttpContext?.Session.GetString("Email")" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProductQRCodeReadWithDynamic - <a asp-area="" asp-controller="Home"
                asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/microsoft/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/microsoft/signalr/dist/browser/signalr.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"
        integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @*<script src="~/js/notification.js"></script>
    <script src="~/js/site.js"></script>*@

    <script>
        var connection = new signalR.HubConnectionBuilder().withUrl("/notificationHub").build();

        //!!! "ReceivedNotification" adlı hub metodu tarafından tetiklenen olay dinleyicisi !!!
        connection.on("ReceivedNotification", function (message)
        {
            alert("notification: " + message);
            OnConnected();
        });
        connection.on("ReceivedPersonalNotification", function (message)
        {
            alert("Email : " + message);
            OnConnected();
        });

        connection.start().then(function ()
        {
            console.log("SignalR connection started.");
            OnConnected();
        }).catch(function (err)
        {
            console.error(err.toString());
        });

        function OnConnected()
        {
            var email = '@HttpContextAccesor.HttpContext.Session.GetString("Email")' ?? "NONE";

            connection.invoke("SaveUserConnection", email).then(function ()
            {
                console.log("SaveUserConnection invoked successfully.");
            }).catch(function (err)
            {
                console.error("Failed to invoke SaveUserConnection: " + err.toString());
            });
        }
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>

</html>